@echo off
echo Killing port 3009...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3009') do taskkill /F /PID %%a 2>nul
echo Removing .next lock files...
if exist ".next\dev" rmdir /s /q ".next\dev" 2>nul
echo Starting Bergen Fitness dev server on port 3009...
start http://localhost:3009
call npm run dev -- --port 3009
